### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by keyserfaty** [fabriceTOUSSAINT/lens-search#6]
Found this repo looking for uses of a library. To answer your question on line 24, `where` returns an array. If you want the first element of the array you can add a `.first()` to the end of the query. Hope it helps :)

https://github.com/fabriceTOUSSAINT/lens-search/blob/ef833db04b5ab69c37626dbf5d56984fc085a1fd/server/src/api/lens.ts#L24

**Comment by fabriceTOUSSAINT** [comment]
oh wow, didn't expect someone to stumble upon this! thanks for the tip! that's certainly good to know.
